# Generated by Django 3.1 on 2020-08-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_de_compra',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
