# Generated by Django 3.1 on 2020-08-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0002_producto_precio_de_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'categoriaProducto', 'verbose_name_plural': 'categoriaProductos'},
        ),
    ]
