# Generated by Django 3.1 on 2020-08-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0003_auto_20200825_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
