# Generated by Django 3.1 on 2020-08-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0004_auto_20200825_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_de_compra',
        ),
    ]
