# Generated by Django 3.1 on 2020-08-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_iva', models.FloatField()),
                ('precio_sin_iva', models.FloatField()),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductosApp.categoriaproducto')),
            ],
        ),
    ]
