# Generated by Django 3.1 on 2020-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0006_stock_precio_de_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
