# Generated by Django 3.1 on 2020-09-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0005_remove_producto_precio_de_compra'),
        ('StockApp', '0007_auto_20200829_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductosApp.producto', unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='precio_de_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
