# Generated by Django 3.1.2 on 2020-10-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0009_auto_20200904_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fecha_stock',
            field=models.DateField(auto_now=True),
        ),
    ]
