# Generated by Django 3.1 on 2020-08-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='issue_quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_updated',
            new_name='fecha_stock',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='created_by',
            new_name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
    ]
