# Generated by Django 3.1 on 2020-08-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0003_auto_20200828_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nombre_producto',
            field=models.CharField(default='', max_length=60),
        ),
    ]
