# Generated by Django 3.1 on 2020-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
